#When loading plugins ignore plugins that don't end with .jar
IgnoreNonJarPlugins: false

#The user agent used to make internet requests
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36